In [1]:
import torch

Creating some tensors:

In [2]:
vect = [1.0, 2.0, 3.0]
vectTensor = torch.tensor(vect)
print(vectTensor)

tensor([1., 2., 3.])


In [4]:
matr = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
matrTensor = torch.tensor(matr)
print(matrTensor)

matr2 = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]
matrTensor2 = torch.tensor(matr2)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


Some basic operations on tensors:

In [5]:
print(matrTensor + matrTensor2)
print(matrTensor * matrTensor2)
print(matrTensor.matmul(matrTensor2))

tensor([[ 2.,  2.,  3.],
        [ 4.,  6.,  6.],
        [ 7.,  8., 10.]])
tensor([[1., 0., 0.],
        [0., 5., 0.],
        [0., 0., 9.]])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


Reshaping tensors:

In [7]:
print(matrTensor.view(1, -1))
print(matrTensor.view(1, 3, -1))

tensor([[1., 0., 0., 0., 1., 0., 0., 0., 1.]])
tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]])
