In [6]:
import torch

Creating some tensors:

In [7]:
vect = [1.0, 2.0, 3.0]
vectTensor = torch.tensor(vect)
print(vectTensor)

tensor([1., 2., 3.])


In [8]:
matr = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
matrTensor = torch.tensor(matr)
print(matrTensor)

matr2 = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]
matrTensor2 = torch.tensor(matr2)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


Some basic operations on tensors:

In [9]:
print(matrTensor + matrTensor2)
print(matrTensor * matrTensor2)
print(matrTensor.matmul(matrTensor2))

tensor([[ 2.,  2.,  3.],
        [ 4.,  6.,  6.],
        [ 7.,  8., 10.]])
tensor([[1., 0., 0.],
        [0., 5., 0.],
        [0., 0., 9.]])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


Reshaping tensors:

In [10]:
print(matrTensor.view(1, -1))
print(matrTensor.view(1, 3, -1))

tensor([[1., 0., 0., 0., 1., 0., 0., 0., 1.]])
tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]])


Scratch work area:

In [13]:
array1 = [1, 2, 3, 4]
array2 = [1, 2, 4, 5]
res = (array1 == array2)
print(res)
t1 = torch.tensor(array1)
t2 = torch.tensor(array2)
res2 = (t1 == t2)
print(res2)
print(res2.sum())

False
tensor([1, 1, 0, 0], dtype=torch.uint8)
2


In [21]:
print(t1.numpy())
t3 = torch.tensor([1, 1, 1, 1])
t1, t2 = t3
print(t1)
print(t2)

[1 2 3 4]


ValueError: too many values to unpack (expected 2)